[project]
name = "gu-ibdm-to-ibdf"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.12.0",
    "pyside6>=6.8.2.1",
]
